# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 791, 81))
        self.widget.setStyleSheet("background-color: rgb(185, 185, 185);\n"
                                  "border:1px solid;\n"
                                  "border-radius:12px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font-weight:bold;\n"
                                 "font-size:30px;\n"
                                 "border:0px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(9, 99, 801, 491))
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 231, 491))
        self.widget_3.setStyleSheet("border:1px solid;\n"
                                    "background-color: rgb(144, 144, 144);\n"
                                    "border-radius:12px;")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 231, 81))
        self.widget_4.setStyleSheet("background-color: rgb(188, 188, 188);\n"
                                    "")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setStyleSheet("font-weight:bold;\n"
                                   "font-size:14px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.list_user = QtWidgets.QListWidget(self.widget_3)
        self.list_user.setGeometry(QtCore.QRect(10, 91, 211, 391))
        self.list_user.setAutoFillBackground(False)
        self.list_user.setStyleSheet("border:0px;\n"
                                     "background-color: rgb(255, 255, 255);")
        self.list_user.setObjectName("list_user")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(239, -1, 551, 491))
        self.widget_5.setStyleSheet("background-color: rgb(144, 144, 144);\n"
                                    "border-radius:12px;")
        self.widget_5.setObjectName("widget_5")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_5)
        self.scrollArea.setGeometry(QtCore.QRect(10, 60, 531, 351))
        self.scrollArea.setStyleSheet("background-color: rgb(166, 166, 166);\n"
                                      "\n"
                                      "border-radius:22px;\n"
                                      "border:1px solid;\n"
                                      "")
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 349))
        self.scrollAreaWidgetContents.setStyleSheet("border:0.5px solid;\n"
                                                    "border-radius:10px;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setStyleSheet("font-size:14px;\n"
                                   "font-weight:bold;\n"
                                   "padding-left:1px;\n"
                                   "border:0px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                         "border-radius:0px;\n"
                                         "\n"
                                         "")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setGeometry(QtCore.QRect(20, 20, 521, 41))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setStyleSheet("font-size:24px;\n"
                                   "font-weight:bold;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setGeometry(QtCore.QRect(9, 420, 531, 61))
        self.widget_7.setStyleSheet("border:1px solid;")
        self.widget_7.setObjectName("widget_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget_7)
        self.scrollArea_2.setGeometry(QtCore.QRect(9, 11, 461, 41))
        self.scrollArea_2.setStyleSheet("border:0px;\n"
                                        "border-radius:0px;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 461, 41))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(0, 0, 451, 41))
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                           "\n"
                                           "border:1px solid;")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.Send = QtWidgets.QPushButton(self.widget_7)
        self.Send.setGeometry(QtCore.QRect(470, 10, 51, 41))
        self.Send.setCheckable(True)
        self.Send.setDefault(False)
        self.Send.setFlat(False)
        self.Send.setObjectName("Send")
        self.plainTextEdit.verticalScrollBar().setValue(self.plainTextEdit.verticalScrollBar().maximum())
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        #MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Chat Room"))
        self.label_2.setText(_translate("MainWindow", "List User"))
        self.label_3.setText(_translate("MainWindow", "Le Huu Minh Vu"))
        self.label_4.setText(_translate("MainWindow", "Chat Box"))
        self.Send.setText(_translate("MainWindow", "attach"))
